---
version: '3.6'
services:
  guardnode:
    image: commerceblock/guardnode:latest
    volumes:
      - ../../ocean:/home/bitcoin/.bitcoin
    command: >-
      python3 -m guardnode
        --rpcuser ${OCEAN_RPC_USER:-ocean}
        --rpcpass ${OCEAN_RPC_PASSWORD:-oceanpass}
        --rpchost ocean:8332
        --servicerpcuser ${OCEAN_RPC_USER:-ocean}
        --servicerpcpass ${OCEAN_RPC_PASSWORD:-oceanpass}
        --servicerpchost ocean:8332
        --bidlimit 50
        --challengehost https://coordinator.testnet.commerceblock.com:10005
        --nodelogfile /home/bitcoin/.bitcoin/ocean_main/debug.log
    depends_on:
      - ocean
  ocean:
    image: commerceblock/ocean:dfd627dca
    networks:
      - default
    ports:
      - "8332:8332"
      - "7042:7042"
    volumes:
      - ../../ocean:/home/bitcoin/.bitcoin
    command: >-
      oceand
        -printtoconsole
        -chain=ocean_main
        -rpcuser=${OCEAN_RPC_USER:-ocean}
        -rpcpassword=${OCEAN_RPC_PASSWORD:-oceanpass}
        -rpcport=8332
        -rpcallowip=0.0.0.0/0
        -addnode=testnet.commerceblock.com
        -txindex=1
        -listen=1
        -signblockscript=53210304d3c198a42e5c8e051c56dc8156fdc681d64a2b0aa5b24be61536d6f9b3be2b2103351b7ec1d3f1f72006f2bb69115d864a4d62be1833db9081df9a1bdd5b95d50221031178d825030d145461a8cbf8e647e21105500f8e36bc291d8c3b58877edcd2372103f8865f1da3f1186297143154327a5569d5214fdeb21fe56b7a7c972059a2e2642103aa21fb4ebabef155e7f56eca0f656bc0628433be451d01229e2b320fa8d5eb3455ae
        -con_mandatorycoinbase=76a9143e6b9f66eeb139c693cc8148285133a5ea96f66488ac
        -initialfreecoins=0
        -policycoins=2100000000000000
        -permissioncoinsdestination=76a9149b45b5f6cfbf562e68c5af288dbafe1ac25605a388ac
        -challengecoinsdestination=76a9145a0f7488e32c4c886773d0198448b7b03783e2b188ac
        -parentgenesisblockhash=d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
        -parentcontract=076c97e1c869072ee22f8c91978c99b4bcb02591
        -fedpegaddress=9178afdf2fc2cbdde30290c0b49f040ff804e06c
        -peginconfirmationdepth=10
        -contractintx=1
        -genesistimestamp=1568700000
        -attestationhash=862244710b778def8209ca90be7d697c686d595da4b90acdf6d2f844da1bfd28
